### ISSUE TITLE
Can someone convert cuda code into pytorch？

### ISSUE THREAD

**Issue by jikerWRN** [kakaxi314/GuideNet#14]
Thanks to the author for his good work and open source code!
Since the core code is written in cuda which is difficult to understand for people who are not familiar with cuda programming. Can someone provide the code for pytorch? 
Thanks!

**Comment by JUGGHM** [comment]
Guide Conv can be implemented the same way as CSPN:
https://github.com/kakaxi314/GuideNet/issues/10
https://github.com/kakaxi314/GuideNet/issues/11
